### ISSUE TITLE
How is this different from futures::executor::block_on ?

### ISSUE THREAD

**Issue by e00E** [zesterer/pollster#21]
The functionality provided by this crate is identical to [`futures::executor::block_on `](https://docs.rs/futures/0.3.28/futures/executor/fn.block_on.html).

I have the following natural questions that I feel deserve to be mentioned in the readme:

What are the differences between the two versions?
If I already depend on `futures` with the `executor` feature, is there any reason to prefer pollster over futures?
If pollster is preferred in that case, why isn't the futures version implemented through pollster?

I'm aware that the readme broaches this topic to some degree t but I feel that the futures crate version deserves special mention because it is not (?) a heavy weight executor part of a larger async framework.

**Comment by notgull** [comment]
> What are the differences between the two versions?

Practically there are no differences between the two implementations. They both use a thread parker/unparker pair as a waker to poll a future until it's completed.

> If I already depend on `futures` with the `executor` feature, is there any reason to prefer pollster over futures?

No, `pollster` primarily exists to provide a way to poll futures to completion in an environment that otherwise does not use a reactor.

> If pollster is preferred in that case, why isn't the futures version implemented through pollster?

The `futures` implementation predates `pollster`. In addition the `futures` crate already has a substantial number of dependencies and adding one more is probably something that they'd like to avoid.

**Comment by zesterer** [comment]
Yep, this is a good summary.

`futures` is a great crate and has a lot to give. If you're already depending on `futures`, then `futures::executor::block_on` is just fine. `pollster` is for applications that don't otherwise care to engage in async work.

A good example of this use-case is 3D games that use `wgpu`. The [`Adapter::request_device`](https://docs.rs/wgpu/latest/wgpu/struct.Adapter.html#method.request_device) function, which needs to be executed to access all interesting crate functionality, is asynchronous but most applications don't care to do anything other than polling in-place until the `Adapter` is ready.

**Comment by zesterer** [comment]
Addressed in 5764258.
